In [74]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [75]:
from keras.layers import Dense
from keras.layers import MaxPooling2D
from keras.layers import Convolution2D
from keras.layers import Flatten
from keras.models import Sequential

## Train Model to check image is face or not

In [76]:
data_frame = pd.read_csv('final_dataset.csv')
data_frame.head(10)

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,2494,2495,2496,2497,2498,2499,Emotion,Age,Color,Gender
0,0,45,52,69,127,148,111,99,106,106,...,15,13,13,10,10,12,Emotion_Happy,Age_below20,E_White,G_Male
1,1,107,109,107,107,107,111,122,119,124,...,72,66,62,63,64,66,Emotion_Happy,Age_20_30,E_White,G_ Female
2,2,159,163,166,171,149,90,65,64,73,...,215,222,224,224,225,227,Emotion_Happy,Age_20_30,E_Hispanic,G_ Female
3,3,178,161,69,32,49,50,40,40,52,...,252,252,253,252,251,249,Emotion_Happy,Age_20_30,E_White,G_ Female
4,4,117,104,100,119,136,160,169,168,159,...,180,177,153,133,153,149,Emotion_Happy,Age_20_30,E_White,G_ Female
5,5,235,236,235,229,217,195,168,139,109,...,56,61,72,82,89,94,Emotion_Neutral,Age_20_30,E_Asian,G_ Female
6,6,119,117,115,113,108,102,97,91,86,...,47,53,55,56,57,58,Emotion_Neutral,Age_below20,E_White,G_ Female
7,7,80,81,81,81,82,82,83,83,84,...,86,86,85,85,85,85,Emotion_Neutral,Age_20_30,E_White,G_ Female
8,8,163,166,167,170,176,183,191,201,208,...,228,229,229,229,229,229,Emotion_Neutral,Age_20_30,E_Asian,G_ Female
9,9,174,174,175,177,177,176,176,175,175,...,150,138,138,148,159,167,Not_Face,0,0,0

In [77]:
data_frame['Emotion'].value_counts()

Not_Face           138
Emotion_Neutral    127
Emotion_Happy       66
Emotion_Sad         10
Emotion_Angry        7
0                    1
Age_30_40            1
Age_above_50         1
Name: Emotion, dtype: int64

In [78]:
def isFace(x):
    
    if x == 'Not_Face':
        return 0
    else:
        return 1

In [79]:
X = data_frame.iloc[:,1:2501]
y = data_frame['Emotion'].apply(isFace)

In [80]:
y

0      1
1      1
2      1
3      1
4      1
5      1
6      1
7      1
8      1
9      0
10     0
11     0
12     0
13     0
14     1
15     1
16     1
17     1
18     1
19     1
20     1
21     1
22     1
23     0
24     0
25     1
26     1
27     1
28     0
29     1
      ..
321    1
322    1
323    1
324    1
325    1
326    1
327    1
328    1
329    1
330    1
331    1
332    1
333    1
334    1
335    1
336    1
337    1
338    0
339    0
340    0
341    1
342    0
343    0
344    0
345    1
346    1
347    1
348    1
349    0
350    1
Name: Emotion, Length: 351, dtype: int64

In [81]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [82]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [83]:
y_train

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1]])

In [84]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [85]:
model_isFace = Sequential()
model_isFace.add(Convolution2D(30,3, input_shape = (50,50,1), activation = 'relu', padding = 'same'))
model_isFace.add(MaxPooling2D(pool_size= (2,2)))
model_isFace.add(Convolution2D(40,3, activation = 'relu', padding = 'same'))
model_isFace.add(Convolution2D(45,3, activation = 'relu', padding = 'same'))
model_isFace.add(MaxPooling2D(pool_size= (2,2))) 
model_isFace.add(Flatten())
model_isFace.add(Dense(output_dim = 128, activation = 'relu'))
model_isFace.add(Dense(output_dim = 1, activation = 'sigmoid'))

C:\Users\Shubham Saxena\AppData\Local\conda\conda\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128)`

C:\Users\Shubham Saxena\AppData\Local\conda\conda\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  if __name__ == '__main__':

In [86]:
model_isFace.compile(optimizer='adam', loss = 'binary_crossentropy', metrics  = ['accuracy'])

In [87]:
trainX = X_train.reshape(X_train.shape[0],50, 50, 1).astype( 'float32' )
testX = X_test.reshape(X_test.shape[0],50, 50, 1).astype( 'float32' )

In [88]:
model_isFace.fit(trainX, y_train, batch_size=30, epochs = 10)

Epoch 1/10
235/235 [==============================] - 3s 12ms/step - loss: 0.7176 - acc: 0.5191
Epoch 2/10
235/235 [==============================] - 1s 6ms/step - loss: 0.6202 - acc: 0.6170
Epoch 3/10
235/235 [==============================] - 1s 6ms/step - loss: 0.5162 - acc: 0.7915
Epoch 4/10
235/235 [==============================] - 2s 8ms/step - loss: 0.5160 - acc: 0.7574
Epoch 5/10
235/235 [==============================] - 2s 7ms/step - loss: 0.5140 - acc: 0.7532
Epoch 6/10
235/235 [==============================] - 2s 8ms/step - loss: 0.4288 - acc: 0.8128
Epoch 7/10
235/235 [==============================] - 2s 7ms/step - loss: 0.3669 - acc: 0.8468
Epoch 8/10
235/235 [==============================] - 2s 7ms/step - loss: 0.3128 - acc: 0.8809
Epoch 9/10
235/235 [==============================] - 2s 7ms/step - loss: 0.2629 - acc: 0.9106A: 0s - loss: 0.2807 - acc: 0.900
Epoch 10/10
235/235 [==============================] - 1s 6ms/step - loss: 0.2260 - acc: 0.9021

In [89]:
score = model_isFace.evaluate(testX, y_test, batch_size=10)

116/116 [==============================] - 1s 4ms/step

In [90]:
score

[0.7142339677646242, 0.6724137931034483]

In [91]:
model_json = model_isFace.to_json()
with open("face_model.json", "w") as json_file:
    json_file.write(model_json)
    
#serialise weights as HDF5

model_isFace.save_weights("face_weights.h5")
print("Saved")

Saved

## Train the model to predict Emotion

In [92]:
data_frame = pd.read_csv('final_dataset.csv')
data_frame.head(10)

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,2494,2495,2496,2497,2498,2499,Emotion,Age,Color,Gender
0,0,45,52,69,127,148,111,99,106,106,...,15,13,13,10,10,12,Emotion_Happy,Age_below20,E_White,G_Male
1,1,107,109,107,107,107,111,122,119,124,...,72,66,62,63,64,66,Emotion_Happy,Age_20_30,E_White,G_ Female
2,2,159,163,166,171,149,90,65,64,73,...,215,222,224,224,225,227,Emotion_Happy,Age_20_30,E_Hispanic,G_ Female
3,3,178,161,69,32,49,50,40,40,52,...,252,252,253,252,251,249,Emotion_Happy,Age_20_30,E_White,G_ Female
4,4,117,104,100,119,136,160,169,168,159,...,180,177,153,133,153,149,Emotion_Happy,Age_20_30,E_White,G_ Female
5,5,235,236,235,229,217,195,168,139,109,...,56,61,72,82,89,94,Emotion_Neutral,Age_20_30,E_Asian,G_ Female
6,6,119,117,115,113,108,102,97,91,86,...,47,53,55,56,57,58,Emotion_Neutral,Age_below20,E_White,G_ Female
7,7,80,81,81,81,82,82,83,83,84,...,86,86,85,85,85,85,Emotion_Neutral,Age_20_30,E_White,G_ Female
8,8,163,166,167,170,176,183,191,201,208,...,228,229,229,229,229,229,Emotion_Neutral,Age_20_30,E_Asian,G_ Female
9,9,174,174,175,177,177,176,176,175,175,...,150,138,138,148,159,167,Not_Face,0,0,0

In [93]:
data_frame['Emotion'].value_counts()

Not_Face           138
Emotion_Neutral    127
Emotion_Happy       66
Emotion_Sad         10
Emotion_Angry        7
0                    1
Age_30_40            1
Age_above_50         1
Name: Emotion, dtype: int64

In [94]:
data_frame = data_frame[data_frame['Emotion']!="Age_30_40"]
data_frame = data_frame[data_frame['Emotion']!="Age_above_50"]
data_frame = data_frame[data_frame['Emotion']!="0"]
data_frame = data_frame[data_frame['Emotion']!="Not_Face"]
data_frame['Emotion'].value_counts()

Emotion_Neutral    127
Emotion_Happy       66
Emotion_Sad         10
Emotion_Angry        7
Name: Emotion, dtype: int64

In [95]:
X = data_frame.iloc[:,1:2501]
y = data_frame['Emotion']

In [96]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [97]:
lb = preprocessing.LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [98]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [99]:
y_train

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0]])

In [100]:
model_emotion = Sequential()
model_emotion.add(Convolution2D(30,3, input_shape = (50,50,1), activation = 'relu', padding = 'same'))
model_emotion.add(MaxPooling2D(pool_size= (2,2)))
model_emotion.add(Convolution2D(40,3, activation = 'relu', padding = 'same'))
model_emotion.add(Convolution2D(45,3, activation = 'relu', padding = 'same'))
model_emotion.add(MaxPooling2D(pool_size= (2,2))) 
model_emotion.add(Flatten())
model_emotion.add(Dense(output_dim = 128, activation = 'relu'))
model_emotion.add(Dense(output_dim = 4, activation = 'softmax'))

C:\Users\Shubham Saxena\AppData\Local\conda\conda\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128)`

C:\Users\Shubham Saxena\AppData\Local\conda\conda\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=4)`
  if __name__ == '__main__':

In [101]:
model_emotion.compile(optimizer='adam', loss = 'categorical_crossentropy', metrics  = ['accuracy'])

In [102]:
trainX = X_train.reshape(X_train.shape[0],50, 50, 1).astype( 'float32' )
testX = X_test.reshape(X_test.shape[0],50, 50, 1).astype( 'float32' )

In [103]:
model_emotion.fit(trainX, y_train, batch_size=30, epochs = 10)

Epoch 1/10
140/140 [==============================] - 2s 13ms/step - loss: 1.0939 - acc: 0.5000
Epoch 2/10
140/140 [==============================] - 1s 10ms/step - loss: 0.8622 - acc: 0.6714
Epoch 3/10
140/140 [==============================] - 1s 6ms/step - loss: 0.8060 - acc: 0.6857
Epoch 4/10
140/140 [==============================] - 1s 6ms/step - loss: 0.7475 - acc: 0.6929
Epoch 5/10
140/140 [==============================] - 1s 6ms/step - loss: 0.6365 - acc: 0.7571
Epoch 6/10
140/140 [==============================] - 1s 6ms/step - loss: 0.5767 - acc: 0.7857
Epoch 7/10
140/140 [==============================] - 1s 6ms/step - loss: 0.4589 - acc: 0.8286
Epoch 8/10
140/140 [==============================] - 1s 6ms/step - loss: 0.3822 - acc: 0.8357
Epoch 9/10
140/140 [==============================] - 1s 6ms/step - loss: 0.3281 - acc: 0.9286
Epoch 10/10
140/140 [==============================] - 1s 6ms/step - loss: 0.2260 - acc: 0.9357

In [104]:
score = model_emotion.evaluate(testX, y_test, batch_size=10)
score

70/70 [==============================] - 0s 6ms/step

[1.2538793427603585, 0.5285714268684387]

In [105]:
model_json = model_emotion.to_json()
with open("emotions_model.json", "w") as json_file:
    json_file.write(model_json)
    
#serialise weights as HDF5

model_emotion.save_weights("emotions_weights.h5")
print("Saved")

Saved

## Train Model to predict Age

In [106]:
data_frame = pd.read_csv('final_dataset.csv')
data_frame.head(10)

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,2494,2495,2496,2497,2498,2499,Emotion,Age,Color,Gender
0,0,45,52,69,127,148,111,99,106,106,...,15,13,13,10,10,12,Emotion_Happy,Age_below20,E_White,G_Male
1,1,107,109,107,107,107,111,122,119,124,...,72,66,62,63,64,66,Emotion_Happy,Age_20_30,E_White,G_ Female
2,2,159,163,166,171,149,90,65,64,73,...,215,222,224,224,225,227,Emotion_Happy,Age_20_30,E_Hispanic,G_ Female
3,3,178,161,69,32,49,50,40,40,52,...,252,252,253,252,251,249,Emotion_Happy,Age_20_30,E_White,G_ Female
4,4,117,104,100,119,136,160,169,168,159,...,180,177,153,133,153,149,Emotion_Happy,Age_20_30,E_White,G_ Female
5,5,235,236,235,229,217,195,168,139,109,...,56,61,72,82,89,94,Emotion_Neutral,Age_20_30,E_Asian,G_ Female
6,6,119,117,115,113,108,102,97,91,86,...,47,53,55,56,57,58,Emotion_Neutral,Age_below20,E_White,G_ Female
7,7,80,81,81,81,82,82,83,83,84,...,86,86,85,85,85,85,Emotion_Neutral,Age_20_30,E_White,G_ Female
8,8,163,166,167,170,176,183,191,201,208,...,228,229,229,229,229,229,Emotion_Neutral,Age_20_30,E_Asian,G_ Female
9,9,174,174,175,177,177,176,176,175,175,...,150,138,138,148,159,167,Not_Face,0,0,0

In [107]:
data_frame['Age'].value_counts()

0                  150
Age_20_30           90
Age_30_40           60
Age_below20         18
Age_40_50           17
Age_above_50        13
Emotion_Neutral      2
Emotion_Happy        1
Name: Age, dtype: int64

In [108]:
data_frame = data_frame[data_frame['Age']!="Emotion_Neutral"]
data_frame = data_frame[data_frame['Age']!="Emotion_Happy"]
data_frame = data_frame[data_frame['Age']!="0"]
data_frame['Age'].value_counts()

Age_20_30       90
Age_30_40       60
Age_below20     18
Age_40_50       17
Age_above_50    13
Name: Age, dtype: int64

In [109]:
X = data_frame.iloc[:,1:2501]
y = data_frame['Age']

In [110]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [111]:
lb = preprocessing.LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [112]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [113]:
y_train

array([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [114]:
model_age = Sequential()
model_age.add(Convolution2D(30,3, input_shape = (50,50,1), activation = 'relu', padding = 'same'))
model_age.add(MaxPooling2D(pool_size= (2,2)))
model_age.add(Convolution2D(40,3, activation = 'relu', padding = 'same'))
model_age.add(Convolution2D(45,3, activation = 'relu', padding = 'same'))
model_age.add(MaxPooling2D(pool_size= (2,2))) 
model_age.add(Flatten())
model_age.add(Dense(output_dim = 128, activation = 'relu'))
model_age.add(Dense(output_dim = 5, activation = 'softmax'))

C:\Users\Shubham Saxena\AppData\Local\conda\conda\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128)`

C:\Users\Shubham Saxena\AppData\Local\conda\conda\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=5)`
  if __name__ == '__main__':

In [117]:
model_age.compile(optimizer='adam', loss = 'categorical_crossentropy', metrics  = ['accuracy'])

In [118]:
trainX = X_train.reshape(X_train.shape[0],50, 50, 1).astype( 'float32' )
testX = X_test.reshape(X_test.shape[0],50, 50, 1).astype( 'float32' )

In [120]:
model_age.fit(trainX, y_train, batch_size=30, epochs = 10)

Epoch 1/10
132/132 [==============================] - 1s 6ms/step - loss: 0.3774 - acc: 0.8712
Epoch 2/10
132/132 [==============================] - 1s 6ms/step - loss: 0.2982 - acc: 0.9167
Epoch 3/10
132/132 [==============================] - 1s 6ms/step - loss: 0.1906 - acc: 0.9318
Epoch 4/10
132/132 [==============================] - 1s 7ms/step - loss: 0.0915 - acc: 0.9848
Epoch 5/10
132/132 [==============================] - 1s 7ms/step - loss: 0.0788 - acc: 0.9621
Epoch 6/10
132/132 [==============================] - 1s 7ms/step - loss: 0.0477 - acc: 0.9924
Epoch 7/10
132/132 [==============================] - 1s 6ms/step - loss: 0.0411 - acc: 0.9924
Epoch 8/10
132/132 [==============================] - 1s 6ms/step - loss: 0.0384 - acc: 0.9848
Epoch 9/10
132/132 [==============================] - 1s 6ms/step - loss: 0.0225 - acc: 0.9924
Epoch 10/10
132/132 [==============================] - 1s 6ms/step - loss: 0.0106 - acc: 1.0000

In [122]:
score = model_age.evaluate(testX, y_test, batch_size=10)
score

66/66 [==============================] - 0s 6ms/step

[3.8956586303132954, 0.4545454549970049]

In [123]:
model_json = model_age.to_json()
with open("age_model.json", "w") as json_file:
    json_file.write(model_json)
    
#serialise weights as HDF5

model_age.save_weights("age_weights.h5")
print("Saved")

Saved

## Train the model to predict Gender

In [124]:
data_frame = pd.read_csv('final_dataset.csv')
data_frame.head(10)

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,2494,2495,2496,2497,2498,2499,Emotion,Age,Color,Gender
0,0,45,52,69,127,148,111,99,106,106,...,15,13,13,10,10,12,Emotion_Happy,Age_below20,E_White,G_Male
1,1,107,109,107,107,107,111,122,119,124,...,72,66,62,63,64,66,Emotion_Happy,Age_20_30,E_White,G_ Female
2,2,159,163,166,171,149,90,65,64,73,...,215,222,224,224,225,227,Emotion_Happy,Age_20_30,E_Hispanic,G_ Female
3,3,178,161,69,32,49,50,40,40,52,...,252,252,253,252,251,249,Emotion_Happy,Age_20_30,E_White,G_ Female
4,4,117,104,100,119,136,160,169,168,159,...,180,177,153,133,153,149,Emotion_Happy,Age_20_30,E_White,G_ Female
5,5,235,236,235,229,217,195,168,139,109,...,56,61,72,82,89,94,Emotion_Neutral,Age_20_30,E_Asian,G_ Female
6,6,119,117,115,113,108,102,97,91,86,...,47,53,55,56,57,58,Emotion_Neutral,Age_below20,E_White,G_ Female
7,7,80,81,81,81,82,82,83,83,84,...,86,86,85,85,85,85,Emotion_Neutral,Age_20_30,E_White,G_ Female
8,8,163,166,167,170,176,183,191,201,208,...,228,229,229,229,229,229,Emotion_Neutral,Age_20_30,E_Asian,G_ Female
9,9,174,174,175,177,177,176,176,175,175,...,150,138,138,148,159,167,Not_Face,0,0,0

In [125]:
data_frame['Gender'].value_counts()

0               152
G_ Female       102
G_Male           87
E_White           5
E_Black           2
E_Asian           1
Age_above_50      1
E_Arab            1
Name: Gender, dtype: int64

In [126]:
data_frame = data_frame[data_frame['Gender']!="E_White"]
data_frame = data_frame[data_frame['Gender']!="E_Black"]
data_frame = data_frame[data_frame['Gender']!="E_Arab"]
data_frame = data_frame[data_frame['Gender']!="E_Asian"]
data_frame = data_frame[data_frame['Gender']!="Age_above_50"]
data_frame = data_frame[data_frame['Gender']!="0"]
data_frame['Gender'].value_counts()

G_ Female    102
G_Male        87
Name: Gender, dtype: int64

In [127]:
X = data_frame.iloc[:,1:2501]
y = data_frame['Gender']

In [128]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [129]:
lb = preprocessing.LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [130]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [131]:
model_gender = Sequential()
model_gender.add(Convolution2D(30,3, input_shape = (50,50,1), activation = 'relu', padding = 'same'))
model_gender.add(MaxPooling2D(pool_size= (2,2)))
model_gender.add(Convolution2D(40,3, activation = 'relu', padding = 'same'))
model_gender.add(Convolution2D(45,3, activation = 'relu', padding = 'same'))
model_gender.add(MaxPooling2D(pool_size= (2,2))) 
model_gender.add(Flatten())
model_gender.add(Dense(output_dim = 128, activation = 'relu'))
model_gender.add(Dense(output_dim = 1, activation = 'sigmoid'))

C:\Users\Shubham Saxena\AppData\Local\conda\conda\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128)`

C:\Users\Shubham Saxena\AppData\Local\conda\conda\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  if __name__ == '__main__':

In [132]:
model_gender.compile(optimizer='adam', loss = 'binary_crossentropy', metrics  = ['accuracy'])

In [134]:
trainX = X_train.reshape(X_train.shape[0],50, 50, 1).astype( 'float32' )
testX = X_test.reshape(X_test.shape[0],50, 50, 1).astype( 'float32' )

In [135]:
model_gender.fit(trainX, y_train, batch_size=30, epochs = 10)

Epoch 1/10
126/126 [==============================] - 2s 15ms/step - loss: 0.7504 - acc: 0.5714
Epoch 2/10
126/126 [==============================] - 1s 6ms/step - loss: 0.6971 - acc: 0.4762
Epoch 3/10
126/126 [==============================] - 1s 6ms/step - loss: 0.6809 - acc: 0.7619
Epoch 4/10
126/126 [==============================] - 1s 6ms/step - loss: 0.6677 - acc: 0.5873
Epoch 5/10
126/126 [==============================] - 1s 6ms/step - loss: 0.6505 - acc: 0.6587
Epoch 6/10
126/126 [==============================] - 1s 6ms/step - loss: 0.5969 - acc: 0.7063
Epoch 7/10
126/126 [==============================] - 1s 6ms/step - loss: 0.5426 - acc: 0.8016
Epoch 8/10
126/126 [==============================] - 1s 6ms/step - loss: 0.4686 - acc: 0.8254
Epoch 9/10
126/126 [==============================] - 1s 7ms/step - loss: 0.4416 - acc: 0.7937
Epoch 10/10
126/126 [==============================] - 1s 8ms/step - loss: 0.3310 - acc: 0.8651

In [137]:
score = model_gender.evaluate(testX, y_test, batch_size=10)
score

63/63 [==============================] - 0s 7ms/step

[0.7925409248897007, 0.5396825444130671]

In [138]:
model_json = model_gender.to_json()
with open("gender_model.json", "w") as json_file:
    json_file.write(model_json)
    
#serialise weights as HDF5

model_gender.save_weights("gender_weights.h5")
print("Saved")

Saved

## Train the model to predict Race

In [139]:
data_frame = pd.read_csv('final_dataset.csv')
data_frame.head(10)

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,2494,2495,2496,2497,2498,2499,Emotion,Age,Color,Gender
0,0,45,52,69,127,148,111,99,106,106,...,15,13,13,10,10,12,Emotion_Happy,Age_below20,E_White,G_Male
1,1,107,109,107,107,107,111,122,119,124,...,72,66,62,63,64,66,Emotion_Happy,Age_20_30,E_White,G_ Female
2,2,159,163,166,171,149,90,65,64,73,...,215,222,224,224,225,227,Emotion_Happy,Age_20_30,E_Hispanic,G_ Female
3,3,178,161,69,32,49,50,40,40,52,...,252,252,253,252,251,249,Emotion_Happy,Age_20_30,E_White,G_ Female
4,4,117,104,100,119,136,160,169,168,159,...,180,177,153,133,153,149,Emotion_Happy,Age_20_30,E_White,G_ Female
5,5,235,236,235,229,217,195,168,139,109,...,56,61,72,82,89,94,Emotion_Neutral,Age_20_30,E_Asian,G_ Female
6,6,119,117,115,113,108,102,97,91,86,...,47,53,55,56,57,58,Emotion_Neutral,Age_below20,E_White,G_ Female
7,7,80,81,81,81,82,82,83,83,84,...,86,86,85,85,85,85,Emotion_Neutral,Age_20_30,E_White,G_ Female
8,8,163,166,167,170,176,183,191,201,208,...,228,229,229,229,229,229,Emotion_Neutral,Age_20_30,E_Asian,G_ Female
9,9,174,174,175,177,177,176,176,175,175,...,150,138,138,148,159,167,Not_Face,0,0,0

In [140]:
data_frame['Color'].value_counts()

0              150
E_White         99
E_Indian        49
E_Black         19
E_Asian         15
E_Hispanic       7
G_ Female        6
G_Male           3
Age_below20      1
Age_30_40        1
E_Arab           1
Name: Color, dtype: int64

In [141]:
data_frame = data_frame[data_frame['Color']!="Age_30_40"]
data_frame = data_frame[data_frame['Color']!="Age_below20"]
data_frame = data_frame[data_frame['Color']!="0"]
data_frame = data_frame[data_frame['Color']!="G_Male"]
data_frame = data_frame[data_frame['Color']!="G_ Female"]
data_frame['Color'].value_counts()

E_White       99
E_Indian      49
E_Black       19
E_Asian       15
E_Hispanic     7
E_Arab         1
Name: Color, dtype: int64

In [142]:
X = data_frame.iloc[:,1:2501]
y = data_frame['Color']

In [143]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [144]:
lb = preprocessing.LabelBinarizer()
y_train = lb.fit_transform(y_train)
y_test = lb.transform(y_test)

In [145]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [146]:
model_race = Sequential()
model_race.add(Convolution2D(30,3, input_shape = (50,50,1), activation = 'relu', padding = 'same'))
model_race.add(MaxPooling2D(pool_size= (2,2)))
model_race.add(Convolution2D(40,3, activation = 'relu', padding = 'same'))
model_race.add(Convolution2D(45,3, activation = 'relu', padding = 'same'))
model_race.add(MaxPooling2D(pool_size= (2,2))) 
model_race.add(Flatten())
model_race.add(Dense(output_dim = 128, activation = 'relu'))
model_race.add(Dense(output_dim = 6, activation = 'softmax'))

C:\Users\Shubham Saxena\AppData\Local\conda\conda\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=128)`

C:\Users\Shubham Saxena\AppData\Local\conda\conda\envs\tfp3.6\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="softmax", units=6)`
  if __name__ == '__main__':

In [147]:
model_race.compile(optimizer='adam', loss = 'categorical_crossentropy', metrics  = ['accuracy'])

In [148]:
trainX = X_train.reshape(X_train.shape[0],50, 50, 1).astype( 'float32' )
testX = X_test.reshape(X_test.shape[0],50, 50, 1).astype( 'float32' )

In [149]:
model_race.fit(trainX, y_train, batch_size=50, epochs = 10)

Epoch 1/10
127/127 [==============================] - 2s 14ms/step - loss: 1.6548 - acc: 0.2598
Epoch 2/10
127/127 [==============================] - 1s 6ms/step - loss: 1.2867 - acc: 0.5276
Epoch 3/10
127/127 [==============================] - 1s 6ms/step - loss: 1.2350 - acc: 0.5276
Epoch 4/10
127/127 [==============================] - 1s 7ms/step - loss: 1.1522 - acc: 0.5276
Epoch 5/10
127/127 [==============================] - 1s 6ms/step - loss: 1.1125 - acc: 0.5354
Epoch 6/10
127/127 [==============================] - 1s 7ms/step - loss: 1.0007 - acc: 0.6142
Epoch 7/10
127/127 [==============================] - 1s 6ms/step - loss: 0.9367 - acc: 0.6299
Epoch 8/10
127/127 [==============================] - 1s 5ms/step - loss: 0.8011 - acc: 0.6929
Epoch 9/10
127/127 [==============================] - 1s 6ms/step - loss: 0.6642 - acc: 0.8504
Epoch 10/10
127/127 [==============================] - 1s 6ms/step - loss: 0.5309 - acc: 0.8346

In [151]:
score = model_race.evaluate(testX, y_test, batch_size=10)
score

63/63 [==============================] - 0s 7ms/step

[1.5415431620582702, 0.4603174688324096]

In [152]:
model_json = model_race.to_json()
with open("race_model.json", "w") as json_file:
    json_file.write(model_json)
    
#serialise weights as HDF5

model_race.save_weights("race_weights.h5")
print("Saved")

Saved